In [28]:
! pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\users\souri\appdata\roaming\python\python312\site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\souri\appdata\roaming\python\python312\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\souri\appdata\roaming\python\python312\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\souri\appdata\roaming\python\python312\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\souri\appdata\roaming\python\python312\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in c:\users\souri\appdata\roaming\python\python312\site-packages (from matplotlib) (2.4.3)
Requirement already satisfied: packaging>=20.0 in c:\users\souri\appdata\roaming\python\python312\site-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=8 in c:\users\souri\appdata\roaming\python\python312\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\souri\appdata\roaming\python\python312\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\souri\appdata\roaming\python\python312\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\souri\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [30]:
trades = pd.read_excel("historical_data.xlsx")
fear = pd.read_excel("fear_greed_index.xlsx")

In [31]:
trades.head()
fear.head()

    timestamp  value classification       date
0  1517463000     30           Fear 2018-02-01
1  1517549400     15   Extreme Fear 2018-02-02
2  1517635800     40           Fear 2018-02-03
3  1517722200     24   Extreme Fear 2018-02-04
4  1517808600     11   Extreme Fear 2018-02-05

In [32]:
trades.columns = trades.columns.str.strip().str.lower().str.replace(" ", "_")
fear.columns = fear.columns.str.strip().str.lower().str.replace(" ", "_")

In [33]:
trades.head()

,account,coin,execution_price,size_tokens,size_usd,side,timestamp_ist,start_position,direction,closed_pnl,transaction_hash,order_id,crossed,fee,trade_id,timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,2024-12-02 22:50:00,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,895000000000000,1730000000000
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,2024-12-02 22:50:00,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,443000000000000,1730000000000
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,2024-12-02 22:50:00,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,660000000000000,1730000000000
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,2024-12-02 22:50:00,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1080000000000000,1730000000000
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,2024-12-02 22:50:00,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1050000000000000,1730000000000

In [34]:
trades.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   account           211224 non-null  object
 1   coin              211224 non-null  object
 2   execution_price   211224 non-null  float64
 3   size_tokens       211224 non-null  float64
 4   size_usd          211224 non-null  float64
 5   side              211224 non-null  object
 6   timestamp_ist     211224 non-null  datetime64[ns]
 7   start_position    211224 non-null  float64
 8   direction         211224 non-null  object
 9   closed_pnl        211224 non-null  float64
 10  transaction_hash  211224 non-null  object
 11  order_id          211224 non-null  int64
 12  crossed           211224 non-null  bool
 13  fee               211224 non-null  float64
 14  trade_id          211224 non-null  int64
 15  timestamp         211224 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(6), int64(3), object(5)
memory usage: 24.4+ MB

In [35]:
#trades['timestamp"] = pd.to_datetime(trades[timestamp], unit = 'ms')
trades['timestamp'] = pd.to_datetime(trades['timestamp'], unit='ms')
fear["date"] = pd.to_datetime (fear['timestamp'], unit = "s")

In [36]:
trades.head()

,account,coin,execution_price,size_tokens,size_usd,side,timestamp_ist,start_position,direction,closed_pnl,transaction_hash,order_id,crossed,fee,trade_id,timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,2024-12-02 22:50:00,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,895000000000000,2024-10-27 03:33:20
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,2024-12-02 22:50:00,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,443000000000000,2024-10-27 03:33:20
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,2024-12-02 22:50:00,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,660000000000000,2024-10-27 03:33:20
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,2024-12-02 22:50:00,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1080000000000000,2024-10-27 03:33:20
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,2024-12-02 22:50:00,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1050000000000000,2024-10-27 03:33:20

In [37]:
trades = trades.dropna()
fear = fear.dropna()

In [38]:
trades['date'] = trades['timestamp'].dt.date
fear['date'] = fear['date'].dt.date

In [39]:
trades['trade_value'] = trades['execution_price'] * trades['size_tokens']

In [40]:
trades['pnl_status'] = np.where(trades['closed_pnl'] > 0, 'profit', 'loss')

In [41]:
merged = pd.merge(trades, fear, on='date', how='left')

In [78]:
#merged.head()

In [47]:
merged = merged.drop(columns = ['timestamp_y'])

In [80]:
#merged.head()

## Key matrix

In [50]:
daily_pnl = trades.groupby(['account', 'date'])['closed_pnl'].sum().reset_index()

In [81]:
#daily_pnl.head()

In [53]:
daily_pnl['closed_pnl'] = daily_pnl['closed_pnl'].astype(int)

In [85]:
win_rate = (trades['closed_pnl'] > 0).mean()
win_rate

np.float64(0.4112648183918494)

In [59]:
avg_trade_size = trades['trade_value'].mean()
avg_trade_size

np.float64(5639.451206388134)

In [82]:
#print(trades.columns)

###  Leverage distribution could not be calculated as the dataset does not contain margin or leverage-related fields.

In [83]:
trades_per_day = trades.groupby('date').size()
#trades_per_day

In [75]:
trades['position_type'] = trades['direction'].apply(
    lambda x: 'Long' if 'Long' in str(x) or x == 'Buy'
    else ('Short' if 'Short' in str(x) or x == 'Sell' else 'Other')
)

In [84]:
long_short = trades['position_type'].value_counts(normalize=True) * 100
#print(long_short.round(2))

In [77]:
merged.to_csv("final_data.csv", index=False)